import type { Product } from './types';

// This data is now only used as a fallback for the admin panel.
export const placeholderProducts: Product[] = [
  {
    id: '1',
    name: 'Monstera Deliciosa',
    slug: 'monstera-deliciosa',
    description: 'Iconic tropical plant with unique, split leaves. A statement piece for any room.',
    price: 35.0,
    category: 'Indoor',
    image: 'https://placehold.co/600x600.png',
    isFeatured: true,
    dataAiHint: 'house plant',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '2',
    name: 'Fiddle Leaf Fig',
    slug: 'fiddle-leaf-fig',
    description: 'A popular indoor tree with large, violin-shaped leaves. Requires bright, indirect light.',
    price: 55.0,
    category: 'Indoor',
    image: 'https://placehold.co/600x600.png',
    isFeatured: false,
    dataAiHint: 'potted tree',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '3',
    name: 'Snake Plant',
    slug: 'snake-plant',
    description: 'Extremely hardy and low-maintenance, known for its air-purifying qualities.',
    price: 25.0,
    category: 'Indoor',
    image: 'https://placehold.co/600x600.png',
    isFeatured: true,
    dataAiHint: 'snake plant',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '4',
    name: 'Terracotta Pot Set',
    slug: 'terracotta-pot-set',
    description: 'Set of three classic terracotta pots, perfect for breathability and root health.',
    price: 22.5,
    category: 'Supplies',
    image: 'https://placehold.co/600x600.png',
    isFeatured: false,
    dataAiHint: 'terracotta pot',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '5',
    name: 'Lavender Bush',
    slug: 'lavender-bush',
    description: 'Aromatic and beautiful, this outdoor plant attracts pollinators and repels pests.',
    price: 18.0,
    category: 'Outdoor',
    image: 'https://placehold.co/600x600.png',
    isFeatured: true,
    dataAiHint: 'lavender plant',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '6',
    name: 'Organic Potting Mix',
    slug: 'organic-potting-mix',
    description: 'A nutrient-rich soil blend to help your plants thrive. Suitable for most houseplants.',
    price: 12.0,
    category: 'Supplies',
    image: 'https://placehold.co/600x600.png',
    isFeatured: false,
    dataAiHint: 'soil bag',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '7',
    name: 'Spider Plant',
    slug: 'spider-plant',
    description: 'Easy to grow and propagate, with arching leaves and baby "spiderettes".',
    price: 20.0,
    category: 'Indoor',
    image: 'https://placehold.co/600x600.png',
    isFeatured: false,
    dataAiHint: 'spider plant',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
  {
    id: '8',
    name: 'Japanese Maple',
    slug: 'japanese-maple',
    description: 'A small, deciduous tree known for its graceful habit and stunning seasonal color.',
    price: 75.0,
    category: 'Outdoor',
    image: 'https://placehold.co/600x600.png',
    isFeatured: true,
    dataAiHint: 'maple tree',
    brand: 'Ajal',
    rating: 4.5,
    numReviews: 10,
    countInStock: 20
  },
];
